# A TOML plugin for argocd:
# https://moonrepo.dev/docs/proto/plugins#toml-plugin
name = "ko"
type = "cli"

[resolve]
git-url = "https://github.com/ko-build/ko"

[platform.linux]
download-file = "ko_{version}_Linux_{arch}.tar.gz"
checksum-file = "checksums.txt"

[platform.macos]
download-file = "ko_{version}_Darwin_{arch}.tar.gz"
checksum-file = "checksums.txt"

[platform.windows]
download-file = "ko_{version}_Windows_{arch}.tar.gz"
checksum-file = "checksums.txt"

[install]
download-url = "https://github.com/ko-build/ko/releases/download/v{version}/{download_file}"

[install.arch]
aarch64 = "arm64"
