# A TOML plugin for argocd:
# https://moonrepo.dev/docs/proto/plugins#toml-plugin
name = "chainsaw"
type = "cli"

[resolve]
git-url = "https://github.com/kyverno/chainsaw"

[platform.linux]
download-file = "chainsaw_linux_{arch}.tar.gz"
checksum-file = "checksums.txt"

[platform.macos]
download-file = "chainsaw_darwin_{arch}.tar.gz"
checksum-file = "checksums.txt"

[platform.windows]
download-file = "chainsaw_windows_{arch}.tar.gz"
checksum-file = "checksums.txt"

[install]
download-url = "https://github.com/kyverno/chainsaw/releases/download/v{version}/{download_file}"

[install.arch]
aarch64 = "arm64"
x86_64 = "amd64"

