# A TOML plugin for argocd:
# https://moonrepo.dev/docs/proto/plugins#toml-plugin
name = "Terragrunt"
type = "cli"

[resolve]
git-url = "https://github.com/gruntwork-io/terragrunt"

[platform.linux]
download-file = "terragrunt_linux_{arch}"

[platform.macos]
download-file = "terragrunt_darwin_{arch}"

[platform.windows]
download-file = "terragrunt_windows_{arch}.exe"

[install]
download-url = "https://github.com/gruntwork-io/terragrunt/releases/download/v{version}/{download_file}"

[install.arch]
aarch64 = "arm64"
x86_64 = "amd64"
x86 = "386"
