# A TOML plugin for argocd:
# https://moonrepo.dev/docs/proto/plugins#toml-plugin
name = "ddev"
type = "cli"

[resolve]
git-url = "https://github.com/ddev/ddev"

[platform.linux]
download-file = "ddev_linux-{arch}.v{version}.tar.gz"
checksum-file = "checksums.txt"

[platform.macos]
download-file = "ddev_macos-{arch}.v{version}.tar.gz"
checksum-file = "checksums.txt"

[platform.windows]
download-file = "ddev_windows-{arch}.v{version}.zip"
checksum-file = "checksums.txt"

[install]
download-url = "https://github.com/ddev/ddev/releases/download/v{version}/{download_file}"

[install.arch]
aarch64 = "arm64"
x86_64 = "amd64"
