# A TOML plugin for argocd:
# https://moonrepo.dev/docs/proto/plugins#toml-plugin
name = "Operator SDK"
type = "cli"

[resolve]
git-url = "https://github.com/operator-framework/operator-sdk"

[platform.linux]
download-file = "operator-sdk_linux_{arch}"
checksum-file = "checksums.txt"

[platform.macos]
download-file = "operator-sdk_darwin_{arch}"
checksum-file = "checksums.txt"

# exe-path = "velero.exe"
[install]
download-url = "https://github.com/operator-framework/operator-sdk/releases/download/v{version}/{download_file}"

[install.arch]
aarch64 = "arm64"
x86_64 = "amd64"
# [install.primary]
# exe-path = "velero"
