# A TOML plugin for argocd:
# https://moonrepo.dev/docs/proto/plugins#toml-plugin
name = "onefetch"
type = "cli"

[resolve]
git-url = "https://github.com/o2sh/onefetch"

[platform.linux]
download-file = "onefetch-linux.tar.gz"

[platform.macos]
download-file = "onefetch-mac.tar.gz"

[platform.windows]
download-file = "onefetch-win.tar.gz"

[install]
download-url = "https://github.com/o2sh/onefetch/releases/download/{version}/{download_file}"
# [install.arch]
# aarch64 = "arm64"
# x86_64 = "amd64"
