# A TOML plugin for proto:
# https://moonrepo.dev/docs/proto/plugins#toml-plugin
name = "kind"
type = "cli"

[platform.linux]
download-file = "kind-linux-{arch}"
checksum-file = "kind-linux-{arch}.sha256sum"

[platform.macos]
download-file = "kind-darwin-{arch}"
checksum-file = "kind-darwin-{arch}.sha256sum"

[platform.windows]
download-file = "kind-windows-{arch}"
checksum-file = "kind-windows-{arch}.sha256sum"

[install]
download-url = "https://github.com/kubernetes-sigs/kind/releases/download/v{version}/{download_file}"
unpack = false

[install.arch]
aarch64 = "arm64"
x86_64 = "amd64"

[resolve]
git-url = "https://github.com/kubernetes-sigs/kind"
