# A TOML plugin for proto:
# https://moonrepo.dev/docs/proto/plugins#toml-plugin
name = "minikube"
type = "cli"

[platform.linux]
download-file = "minikube-linux-{arch}"
checksum-file = "minikube-linux-{arch}.sha256"

[platform.macos]
download-file = "minikube-darwin-{arch}"
checksum-file = "minikube-darwin-{arch}.sha256"

[platform.windows]
download-file = "minikube-windows-{arch}.exe"
checksum-file = "minikube-windows-{arch}.exe.sha256"

[install]
download-url = "https://github.com/kubernetes/minikube/releases/download/v{version}/{download_file}"
unpack = false

[install.arch]
aarch64 = "arm64"
x86_64 = "amd64"
x86 = "386"

[resolve]
git-url = "https://github.com/kubernetes/minikube"
