# A TOML plugin for argocd:
# https://moonrepo.dev/docs/proto/plugins#toml-plugin
name = "buildctl"
type = "cli"

[resolve]
git-url = "https://github.com/moby/buildkit"

[platform.linux]
download-file = "buildkit-v{version}.linux-{arch}.tar.gz"

[platform.macos]
download-file = "buildkit-v{version}.darwin-{arch}.tar.gz"

[platform.windows]
download-file = "buildkit-v{version}.windows-{arch}.tar.gz"

[install]
download-url = "https://github.com/moby/buildkit/releases/download/v{version}/{download_file}"

[install.arch]
aarch64 = "arm64"
x86_64 = "amd64"

[install.libc]
gnu = "glibc"

# musl = "musl"
[install.primary]
exe-path = "bin/buildctl"
