name = "Golang Migrate"
type = "cli"

[resolve]
git-url = "https://github.com/golang-migrate/migrate"

[platform.linux]
download-file = "migrate.linux-{arch}.tar.gz"
checksum-file = "sha256sum.txt"

[platform.macos]
download-file = "migrate.darwin-{arch}.tar.gz"
checksum-file = "sha256sum.txt"

[platform.windows]
download-file = "migrate.windows-{arch}.zip"
checksum-file = "sha256sum.txt"

[install]
download-url = "https://github.com/golang-migrate/migrate/releases/download/v{version}/{download_file}"
checksum-url = "https://github.com/golang-migrate/migrate/releases/download/v{version}/{checksum_file}"

[install.arch]
arm = "armv7"
aarch64 = "arm64"
x86 = "386"
x86_64 = "amd64"
