# A TOML plugin for argocd:
# https://moonrepo.dev/docs/proto/plugins#toml-plugin
name = "OpenTofu"
type = "cli"

[resolve]
git-url = "https://github.com/opentofu/opentofu"

[platform.linux]
download-file = "tofu_{version}_linux_{arch}.zip"
checksum-file = "tofu_{version}_SHA256SUMS"

# exe-path = "tofu"
[platform.macos]
download-file = "tofu_{version}_darwin_{arch}.zip"
checksum-file = "tofu_{version}_SHA256SUMS"

# exe-path = "tofu"
[platform.windows]
download-file = "tofu_{version}_windows_{arch}.zip"
checksum-file = "tofu_{version}_SHA256SUMS"

# exe-path = "tofu.exe"
[install]
download-url = "https://github.com/opentofu/opentofu/releases/download/v{version}/{download_file}"

[install.arch]
aarch64 = "arm64"
x86_64 = "amd64"
# [install.primary]
# exe-path = "tofu"
