# A TOML plugin for argocd:
# https://moonrepo.dev/docs/proto/plugins#toml-plugin
name = "Step CA"
type = "cli"

[resolve]
git-url = "https://github.com/smallstep/certificates"

[platform.linux]
download-file = "step-ca_linux_{version}_{arch}.tar.gz"
checksum-file = "checksums.txt"

[platform.macos]
download-file = "step-ca_darwin_{version}_{arch}.tar.gz"
checksum-file = "checksums.txt"

[platform.windows]
download-file = "step-ca_windows_{version}_{arch}.zip"
checksum-file = "checksums.txt"

[install]
download-url = "https://github.com/smallstep/certificates/releases/download/v{version}/{download_file}"

[install.arch]
aarch64 = "arm64"
x86_64 = "amd64"
