# A TOML plugin for argocd:
# https://moonrepo.dev/docs/proto/plugins#toml-plugin
name = "GitLab CLI"
type = "cli"

[resolve]
git-url = "https://gitlab.com/gitlab-org/cli"

[platform.linux]
download-file = "glab_{version}_Linux_{arch}.tar.gz"
checksum-file = "checksums.txt"

[platform.macos]
download-file = "glab_{version}_macOS_{arch}.tar.gz"
checksum-file = "checksums.txt"

[platform.windows]
download-file = "glab_{version}_Windows_{arch}.zip"
checksum-file = "checksums.txt"

[install]
download-url = "https://gitlab.com/gitlab-org/cli/-/releases/v{version}/downloads/{download_file}"

[install.primary]
exe-path = "bin/glab"

[install.arch]
aarch64 = "arm64"
# x86_64 = "amd64"
